defaults:
  - /datamodule/t4dataset/datasets/default_segdet3d_test_dataset@_here_
  - segmentation3d@dataset_tasks.Segmentation3D: default_segmentation3d
  - _self_

_target_: autoware_ml.datamodule.nuscenes.dataset.NuScenesDataset
