# @package _global_

defaults:
  - /tasks/detection3d/ptv3/base
  - _self_

class_names:
  - car
  - truck
  - construction_vehicle
  - bus
  - trailer
  - barrier
  - motorcycle
  - bicycle
  - pedestrian
  - traffic_cone
num_classes: 10
name_mapping: null

grid_size: 0.05
point_cloud_range: [-102.4, -102.4, -3.0, 102.4, 102.4, 5.0]
point_cloud_bev_range: [-102.4, -102.4, 102.4, 102.4]

bev_stride: 4
bev_output_shape: [1024, 1024]
head_voxel_size: [0.2, 0.2, 8.0]

train_sweeps_num: 1
val_sweeps_num: 1

datamodule:
  _target_: autoware_ml.datamodule.nuscenes.detection3d.NuscenesDetection3DDataModule
  data_root: ${oc.env:AUTOWARE_ML_DATA_PATH}/nuscenes
  train_ann_file: nuscenes_infos_train.pkl
  val_ann_file: nuscenes_infos_val.pkl
  test_ann_file: nuscenes_infos_val.pkl
  class_names: ${class_names}
  name_mapping: ${name_mapping}
  train_frame_sampling: null

model:
  export_output_names: [heatmap, reg, height, dim, rot, vel]
  metric:
    _target_: autoware_ml.metrics.detection3d.CenterDistanceMeanAP
    class_names: ${class_names}
    thresholds: [0.5, 1.0, 2.0, 4.0]
    eval_class_range:
      car: 102.0
      truck: 102.0
      construction_vehicle: 102.0
      bus: 102.0
      trailer: 102.0
      barrier: 102.0
      motorcycle: 102.0
      bicycle: 102.0
      pedestrian: 102.0
      traffic_cone: 102.0
    min_point_numbers: 0
    ranges:
      - _target_: autoware_ml.metrics.detection3d.DetectionRange
        name: 0-50m
        min_distance: 0.0
        max_distance: 50.0
      - _target_: autoware_ml.metrics.detection3d.DetectionRange
        name: 50-90m
        min_distance: 50.0
        max_distance: 90.0
      - _target_: autoware_ml.metrics.detection3d.DetectionRange
        name: 90-102m
        min_distance: 90.0
        max_distance: 102.0
  bbox_head:
    _target_: autoware_ml.models.detection3d.heads.centerpoint.CenterHead
    in_channels: 128
    num_classes: ${num_classes}
    class_names: ${class_names}
    shared_channels: 64
    point_cloud_range: ${point_cloud_range}
    voxel_size: ${head_voxel_size}
    out_size_factor: ${head_out_size_factor}
    max_objs: 500
    min_radius: 2
    score_threshold: ${score_threshold}
    post_max_size: ${post_max_size}
    nms_min_radius: ${nms_min_radius}
    heatmap_init_bias: -2.19
    use_velocity: true
