# @package _global_

defaults:
  - /tasks/detection3d/ptv3/base
  - _self_

grid_size: 0.05
point_cloud_range: [-128.0, -128.0, -3.0, 128.0, 128.0, 5.0]
point_cloud_bev_range: [-128.0, -128.0, 128.0, 128.0]

bev_stride: 4
bev_output_shape: [1280, 1280]
head_voxel_size: [0.2, 0.2, 8.0]
post_center_range: [-138.0, -138.0, -5.0, 138.0, 138.0, 12.0]
code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.2]
num_proposals: 200
detection_filter_attributes:
  - [bicycle, cycle_state.without_rider]
  - [motorcycle, vehicle_state.parked]
  - [motorcycle, motorcycle_state.without_rider]

datamodule:
  filter_attributes: ${detection_filter_attributes}
  min_num_lidar_points: ${train_min_num_lidar_points}
  use_valid_flag: ${detection_use_valid_flag}

model:
  export_output_names:
    [
      dense_heatmap,
      query_heatmap_score,
      query_labels,
      heatmap,
      center,
      height,
      dim,
      rot,
      vel,
    ]
  bbox_head:
    _target_: autoware_ml.models.detection3d.heads.transfusion.TransFusionHead
    num_proposals: ${num_proposals}
    auxiliary: true
    in_channels: 128
    hidden_channel: 128
    num_classes: ${num_classes}
    class_names: ${class_names}
    dense_heatmap_pooling_classes: [car, truck, bus, bicycle]
    num_decoder_layers: 1
    num_heads: 8
    feedforward_channels: 256
    common_heads:
      center: [2, 2]
      height: [1, 2]
      dim: [3, 2]
      rot: [2, 2]
      vel: [2, 2]
    bbox_coder:
      _target_: autoware_ml.models.detection3d.task_modules.bbox_coders.TransFusionBBoxCoder
      pc_range: ${point_cloud_range}
      voxel_size: ${head_voxel_size}
      out_size_factor: ${head_out_size_factor}
      post_center_range: ${post_center_range}
      score_threshold: 0.0
      code_size: 10
    assigner:
      _target_: autoware_ml.models.detection3d.task_modules.assigners.HungarianAssigner3D
      cls_cost:
        _target_: autoware_ml.models.detection3d.task_modules.match_costs.ClassificationCost
        weight: 0.15
        alpha: 0.25
        gamma: 2.0
      reg_cost:
        _target_: autoware_ml.models.detection3d.task_modules.match_costs.BBoxBEVL1Cost
        weight: 0.25
      iou_cost:
        _target_: autoware_ml.models.detection3d.task_modules.match_costs.IoU3DCost
        weight: 0.25
    point_cloud_range: ${point_cloud_range}
    voxel_size: ${head_voxel_size}
    out_size_factor: ${head_out_size_factor}
    code_weights: ${code_weights}
    min_radius: 2
    gaussian_overlap: 0.1
    score_threshold: ${score_threshold}
    post_max_size: ${post_max_size}
    nms_min_radius: ${nms_min_radius}
    loss_cls_weight: 1.0
    loss_bbox_weight: 0.25
    loss_heatmap_weight: 1.0
    heatmap_target: oriented
    heatmap_init_bias: -2.19
    nms_kernel_size: 3
    use_velocity: true

deploy:
  onnx:
    modules:
      det3d_head:
        modify_graph:
          _target_: autoware_ml.utils.onnx_modifiers.TransHeadTensorRTModifier
          k: ${num_proposals}
          topk_node_name_substring: /bbox_head/TopK
          attention_node_name_substring: /bbox_head/decoder
