pixi_version: 0.66.0
pixi_install_dir: "{{ ansible_env.HOME }}/.pixi/bin"
pixi_archive_map:
  x86_64: pixi-x86_64-unknown-linux-musl.tar.gz
  aarch64: pixi-aarch64-unknown-linux-musl.tar.gz
  arm64: pixi-aarch64-unknown-linux-musl.tar.gz
