# @package _global_
defaults:
  - /tasks/detection3d/transfusion/base
  - /datasets/nuscenes/detection3d
  - /datasets/nuscenes/lidar
  - /database@database: nuscenes/nuscenes_base
  - /datamodule@datamodule: nuscenes/default_detection3d_datamodule
  - _self_

batch_size: 16
num_workers: 8

dataset: ${nuscenes}

point_cloud_range: [-54.0, -54.0, -5.0, 54.0, 54.0, 3.0]
voxel_size: [0.075, 0.075, 0.2]
out_size_factor: 8

datamodule:
  train_dataset:
    transforms:
      _target_: autoware_ml.transforms.base.TransformsCompose
      _convert_: all
      pipeline:
        - _target_: autoware_ml.transforms.point_cloud.loading.LoadPointsFromFile
          _convert_: all
          use_dim: [0, 1, 2, 3] # Refer PointFieldIndex for the name of each dimensionality, [x, y, z, intensity]
          bev_remove_radius: 0.0
        - _target_: autoware_ml.transforms.point_cloud.loading.LoadMultiSweepPointsFromFile
          _convert_: all
          past:
            _target_: autoware_ml.transforms.point_cloud.loading.SweepWindow
            num: 9
            time_lag_range: [0.025, 0.475]
            selection: nearest
          bev_remove_radius: 1.0
          use_timestamp_difference: false
          use_dim: [0, 1, 2, 3] # Refer PointFieldIndex for the name of each dimensionality, [x, y, z, intensity]
        - _target_: autoware_ml.transforms.point_cloud.geometry.GlobalRotScaleTrans
          _convert_: all
          # In radians, the range of rotation angles for random rotation around the Z-axis.
          # The range is specified as [min_angle, max_angle].
          yaw_rot_range: [-0.78539816, 0.78539816]
          # The range of scale factors for random scaling.
          scale_ratio_range: [0.9, 1.1]
          # The standard deviation for Gaussian translation noise.
          translation_std: [0.5, 0.5, 0.2]
        - _target_: autoware_ml.transforms.point_cloud.geometry.GlobalBEVRandomFlip
          _convert_: all
          horizontal_flip_ratio: 0.5
          vertical_flip_ratio: 0.5
        - _target_: autoware_ml.transforms.point_cloud.geometry.PointsRangeFilter
          _convert_: all
          points_range: ${point_cloud_range}
        - _target_: autoware_ml.transforms.point_cloud.geometry.PointsRandomShuffle
          _convert_: all
        - _target_: autoware_ml.transforms.boxes3d.filters.BBoxesLabelNameFilter
          _convert_: all
          label_names_to_keep: ${database.taxonomy.detection3d.class_names}
          class_names: ${database.taxonomy.detection3d.class_names}
        - _target_: autoware_ml.transforms.boxes3d.filters.BBoxesAttributeFilter
          _convert_: all
          filter_attributes: ${dataset.detection3d.filter_attributes}
        - _target_: autoware_ml.transforms.boxes3d.filters.BBoxesRangeFilter
          _convert_: all
          point_cloud_range: ${point_cloud_range}
        - _target_: autoware_ml.transforms.boxes3d.filters.BBoxesMinPointsFilter
          _convert_: all
          min_points: 1
          bev_range: [-60.0, -60.0, 60.0, 60.0]
  test_dataset:
    transforms:
      _target_: autoware_ml.transforms.base.TransformsCompose
      _convert_: all
      pipeline:
        - _target_: autoware_ml.transforms.point_cloud.loading.LoadPointsFromFile
          _convert_: all
          use_dim: [0, 1, 2, 3]
          bev_remove_radius: 0.0
        - _target_: autoware_ml.transforms.point_cloud.loading.LoadMultiSweepPointsFromFile
          _convert_: all
          past:
            _target_: autoware_ml.transforms.point_cloud.loading.SweepWindow
            num: 9
            time_lag_range: [0.025, 0.475]
            selection: nearest
          bev_remove_radius: 1.0
          use_timestamp_difference: false
          use_dim: [0, 1, 2, 3] # Refer PointFieldIndex for the name of each dimensionality, [x, y, z, intensity]
        - _target_: autoware_ml.transforms.point_cloud.geometry.PointsRangeFilter
          _convert_: all
          points_range: ${point_cloud_range}
        - _target_: autoware_ml.transforms.boxes3d.filters.BBoxesLabelNameFilter
          _convert_: all
          label_names_to_keep: ${database.taxonomy.detection3d.class_names}
          class_names: ${database.taxonomy.detection3d.class_names}
  train_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
    shuffle: true
  validation_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
  test_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}

model:
  pts_middle_encoder:
    sparse_shape: [1440, 1440, 41]
    dense_output_shapes: [180, 180, 2]
  bbox_head:
    num_proposals: 200
    nms_min_radius: 1.0
    bbox_coder:
      post_center_range: [-61.2, -61.2, -10.0, 61.2, 61.2, 10.0]

trainer:
  max_epochs: 30
