# @package _global_
defaults:
  - /tasks/detection3d/transfusion/base
  - /datasets/t4dataset/detection3d
  - /datasets/t4dataset/lidar
  - /database@database: t4dataset/t4dataset_j6gen2_base
  - /datamodule@datamodule: t4dataset/default_detection3d_datamodule
  - override /datamodule/transforms@datamodule.train_dataset.transforms: transfusion_train_transforms
  - override /datamodule/transforms@datamodule.test_dataset.transforms: transfusion_test_transforms
  - _self_

batch_size: 16
num_workers: 8

dataset: ${t4dataset}

point_cloud_range: [-122.4, -122.4, -3.0, 122.4, 122.4, 5.0]
voxel_size: [0.17, 0.17, 0.2]
out_size_factor: 8

datamodule:
  train_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
    shuffle: true
  validation_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
  test_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}

model:
  pts_middle_encoder:
    sparse_shape: [1440, 1440, 41]
    dense_output_shapes: [180, 180, 2]
  bbox_head:
    num_proposals: 500
    nms_min_radius: 1.0
    bbox_coder:
      post_center_range: [-200.0, -200.0, -10.0, 200.0, 200.0, 10.0]
  scheduler:
    max_lr_factor: 5.0

trainer:
  max_epochs: 30
