_target_: autoware_ml.databases.t4datasets.t4database.T4Database
_convert_: all

database_version: T4Detection3d-j6gen2_base-v1.0.0
# Root path of actual annotation files
database_root_path: ${data_root_path}/t4datasets/
# Root path where the scenario yaml files are stored
scenario_root_path: ${working_dir}/perception-devops/dataset_annotation/t4datasets/detection3d/
cache_path: ${cache_root_path}/detection3d/
# Prefix name of the cache file, it will be <cache_file_prefix_name>_<database_hash>.parquet
cache_file_prefix_name: database

# Read each database into their corresponding scenarios, it will run evaluation/visualization on each scenario
defaults:
  - t4datasets/scenarios@scenarios.db_j6gen2_base: detection3d/db_j6gen2_base
  - t4datasets/scenarios@scenarios.db_j6gen2: detection3d/db_j6gen2
  - t4datasets/scenarios@scenarios.db_largebus: detection3d/db_largebus

# The main database is the database that will be used to train the model
main_database: db_j6gen2_base

# Processor settings
num_workers: 16