# @package _global_
defaults:
  - /defaults/default_runtime
  - _self_

data_root: ${oc.env:AUTOWARE_ML_DATA_PATH}/t4dataset

datamodule:
  _target_: autoware_ml.datamodule.t4dataset.lidar_calibration_status.T4LidarCalibrationDataModule
  data_root: ${data_root}
  train_ann_file: ${data_root}/calibration_info_lidarseg/t4dataset_gen2_lidarseg_infos_train.pkl
  val_ann_file: ${data_root}/calibration_info_lidarseg/t4dataset_gen2_lidarseg_infos_val.pkl
  test_ann_file: ${data_root}/calibration_info_lidarseg/t4dataset_gen2_lidarseg_infos_test.pkl
  lidar_source1: LIDAR_FRONT_UPPER
  lidar_source2: LIDAR_FRONT_LOWER
  stack_keys: [fused_img, gt_calibration_status]
  train_dataloader_cfg:
    batch_size: 8
    num_workers: 4
    shuffle: true
  val_dataloader_cfg:
    batch_size: 8
    num_workers: 4
  test_dataloader_cfg:
    batch_size: 8
    num_workers: 4
  predict_dataloader_cfg:
    batch_size: 1
    num_workers: 1
  train_transforms:
    pipeline:
      - _target_: autoware_ml.transforms.lidar.LidarLidarCalibrationMisalignment
        p: 0.5
        activate_roll: false
        activate_pitch: false
        activate_yaw: true
        activate_x: false
        activate_y: false
        activate_z: false
        min_yaw_neg: 2.0
        max_yaw_neg: 4.0
        min_yaw_pos: 2.0
        max_yaw_pos: 4.0
      - _target_: autoware_ml.transforms.lidar.LidarLidarFusion
        width: 1024
        height: 512
        projection: pinhole
        max_depth: 80.0
      - _target_: autoware_ml.transforms.lidar.SaveFusionPreview
        p: 0.1
        out_dir: ${hydra:run.dir}/previews
      - _target_: autoware_ml.transforms.common.PermuteAxes
        input_keys: [fused_img]
        axes: [2, 0, 1]
  val_transforms:
    pipeline:
      - _target_: autoware_ml.transforms.lidar.LidarLidarCalibrationMisalignment
        p: 0.5
        activate_roll: false
        activate_pitch: false
        activate_yaw: true
        activate_x: false
        activate_y: false
        activate_z: false
        min_yaw_neg: 2.0
        max_yaw_neg: 4.0
        min_yaw_pos: 2.0
        max_yaw_pos: 4.0
      - _target_: autoware_ml.transforms.lidar.LidarLidarFusion
        width: 1024
        height: 512
        projection: pinhole
        max_depth: 80.0
      - _target_: autoware_ml.transforms.common.PermuteAxes
        input_keys: [fused_img]
        axes: [2, 0, 1]
  test_transforms:
    pipeline:
      - _target_: autoware_ml.transforms.lidar.LidarLidarCalibrationMisalignment
        p: 0.5
        activate_roll: false
        activate_pitch: false
        activate_yaw: true
        activate_x: false
        activate_y: false
        activate_z: false
        min_yaw_neg: 2.0
        max_yaw_neg: 4.0
        min_yaw_pos: 2.0
        max_yaw_pos: 4.0
      - _target_: autoware_ml.transforms.lidar.LidarLidarFusion
        width: 1024
        height: 512
        projection: pinhole
        max_depth: 80.0
      - _target_: autoware_ml.transforms.common.PermuteAxes
        input_keys: [fused_img]
        axes: [2, 0, 1]
  predict_transforms:
    pipeline:
      - _target_: autoware_ml.transforms.lidar.LidarLidarCalibrationMisalignment
        p: 0.5
        activate_roll: false
        activate_pitch: false
        activate_yaw: true
        activate_x: false
        activate_y: false
        activate_z: false
        min_yaw_neg: 2.0
        max_yaw_neg: 4.0
        min_yaw_pos: 2.0
        max_yaw_pos: 4.0
      - _target_: autoware_ml.transforms.lidar.LidarLidarFusion
        width: 1024
        height: 512
        projection: pinhole
        max_depth: 80.0
      - _target_: autoware_ml.transforms.common.PermuteAxes
        input_keys: [fused_img]
        axes: [2, 0, 1]

model:
  _target_: autoware_ml.models.calibration_status.CalibrationStatusClassifier
  backbone:
    _target_: autoware_ml.models.common.backbones.resnet.ResNet18
    in_channels: 4
  neck:
    _target_: autoware_ml.models.common.necks.global_average_pooling.GlobalAveragePooling
  head:
    _target_: autoware_ml.models.common.heads.linear_cls_head.LinearClsHead
    num_classes: 2
    in_channels: 512
    loss:
      _target_: torch.nn.CrossEntropyLoss
    topk: [1]
    cal_acc: true
  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.001
    weight_decay: 0.01
    betas: [0.9, 0.999]
    eps: 1e-8
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    T_max: 20
    eta_min: 1e-8
    last_epoch: -1

trainer:
  max_epochs: 30
  gradient_clip_val: 10.0
  gradient_clip_algorithm: norm
