- repository: autowarefoundation/sync-file-templates
  source-dir: sources
  files:
    - source: .github/dependabot.yaml
    - source: .github/stale.yml
    - source: .github/workflows/github-release.yaml
    - source: .github/workflows/pre-commit-optional-autoupdate.yaml
    - source: .github/workflows/pre-commit-autoupdate.yaml
    - source: .github/workflows/semantic-pull-request.yaml
    - source: .github/workflows/spell-check-differential.yaml
      pre-commands: |
        sd "        with:\n" "        with:\n          local-cspell-json: .cspell.json\n" {source}
    - source: .github/workflows/spell-check-daily.yaml
      pre-commands: |
        sd "        with:\n" "        with:\n          local-cspell-json: .cspell.json\n" {source}
    - source: .github/workflows/sync-files.yaml
    - source: .markdown-link-check.json
    - source: .markdownlint.yaml
    - source: .yamllint.yaml
