# @package _global_
defaults:
  - /tasks/segmentation3d/frnet/base
  - /datasets/nuscenes/segmentation3d
  - /datasets/nuscenes/lidar
  - /database@database: nuscenes/nuscenes_base
  - /datamodule@datamodule: nuscenes/default_segmentation3d_datamodule
  - override /datamodule/transforms@datamodule.train_dataset.transforms: frnet_train_transforms
  - override /datamodule/transforms@datamodule.validation_dataset.transforms: frnet_test_transforms
  - override /datamodule/transforms@datamodule.test_dataset.transforms: frnet_test_transforms
  - _self_

batch_size: 16
num_workers: 8

dataset: ${nuscenes}

fov_up: 10.0
fov_down: -30.0
range_height: 32
range_width: 1920
frustum_height: 32
frustum_width: 480

datamodule:
  train_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
    shuffle: true
  validation_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
  test_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
