# @package _global_
defaults:
  - /tasks/segmentation3d/frnet/base
  - /datasets/t4dataset/segmentation3d
  - /datasets/t4dataset/lidar
  - /database@database: t4dataset/t4dataset_j6gen2_semaseg
  - /datamodule@datamodule: t4dataset/default_segmentation3d_datamodule
  - _self_

batch_size: 4
num_workers: 8

dataset: ${t4dataset}

fov_up: 15.0
fov_down: -25.0
range_height: 128
range_width: 4096
frustum_height: 128
frustum_width: 1024

# One sample per lidar
lidar_sources:
  - LIDAR_FRONT_UPPER
  - LIDAR_LEFT_UPPER
  - LIDAR_RIGHT_UPPER
  - LIDAR_REAR_UPPER

datamodule:
  train_dataset:
    lidar_sources: ${lidar_sources}
    transforms:
      _target_: autoware_ml.transforms.base.TransformsCompose
      _convert_: all
      pipeline:
        - _target_: autoware_ml.transforms.point_cloud.loading.LoadPointsFromFile
          _convert_: all
          use_dim: [0, 1, 2, 3]
          bev_remove_radius: 0.0
        - _target_: autoware_ml.transforms.point_cloud.geometry.GlobalBEVRandomFlip
          _convert_: all
          horizontal_flip_ratio: 0.5
          vertical_flip_ratio: 0.5
        - _target_: autoware_ml.transforms.point_cloud.geometry.GlobalRotScaleTrans
          _convert_: all
          yaw_rot_range: [-3.14159265, 3.14159265]
          scale_ratio_range: [0.95, 1.05]
          translation_std: [0.1, 0.1, 0.1]
  test_dataset:
    lidar_sources: ${lidar_sources}
    transforms:
      _target_: autoware_ml.transforms.base.TransformsCompose
      _convert_: all
      pipeline:
        - _target_: autoware_ml.transforms.point_cloud.loading.LoadPointsFromFile
          _convert_: all
          use_dim: [0, 1, 2, 3]
          bev_remove_radius: 0.0
  train_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
    shuffle: true
  validation_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
  test_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
