_target_: autoware_ml.datamodule.data_module.DataModule
_convert_: all

defaults:
  - /datamodule/splitter@splitter: default_scenario_splitter
  - /datamodule/dataloader@train_dataloader: default_dataloader
  - /datamodule/dataloader@validation_dataloader: default_dataloader
  - /datamodule/dataloader@test_dataloader: default_dataloader
  - /datamodule/dataloader@predict_dataloader: default_dataloader
  - nuscenes/datasets@train_dataset: default_segdet3d_train_dataset
  - nuscenes/datasets@test_dataset: default_segdet3d_test_dataset
  - nuscenes/datasets@validation_dataset: default_segdet3d_test_dataset

database: ${database}

predict_dataset: null
