defaults:
  - default_datamodule@_here_
  - t4dataset/datasets@train_dataset: default_multiview_detection3d_train_dataset
  - t4dataset/datasets@test_dataset: default_multiview_detection3d_test_dataset
