_target_: autoware_ml.datamodule.t4dataset.dataset.T4Dataset
_convert_: all

defaults:
  - segmentation3d@dataset_tasks.Segmentation3D: default_segmentation3d
  - ../../transforms@transforms: default_segmentation3d_train_transforms

database_root_path: ${database.root_path}
lidar_intensity_scale: ${database.lidar_intensity_scale}

# Always None since we run splitter in the process
dataset_records_dataframe: null

max_num_3d_gt_bboxes: 0
