_target_: autoware_ml.datamodule.t4dataset.dataset.T4Dataset
_convert_: all
_partial_: true

defaults:
  - detection3d@dataset_tasks.Detection3D: default_detection3d
  - /datamodule/transforms@transforms: default_multiview_detection3d_test_transforms

max_num_3d_gt_bboxes: 500
