# @package _global_
defaults:
  - /tasks/segmentation3d/ptv3/base
  - /datasets/nuscenes/segmentation3d
  - /datasets/nuscenes/lidar
  - /database@database: nuscenes/nuscenes_base
  - /datamodule@datamodule: nuscenes/default_segmentation3d_datamodule
  - _self_

batch_size: 16
num_workers: 8

dataset: ${nuscenes}
max_voxels: 524288
grid_size: 0.05
point_cloud_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]

datamodule:
  train_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
    shuffle: true
  validation_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
  test_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
