# @package _global_
defaults:
  - /tasks/segmentation3d/ptv3/base
  - _self_

ignore_index: 16
max_label: 31
num_classes: 16
mix_prob: 0.8
grid_size: 0.05
point_cloud_range: [-102.4, -102.4, -2.8, 102.4, 102.4, 10.0]

seg_label_mapping:
  0: ${ignore_index}
  1: ${ignore_index}
  2: 6
  3: 6
  4: 6
  5: ${ignore_index}
  6: 6
  7: ${ignore_index}
  8: ${ignore_index}
  9: 0
  10: ${ignore_index}
  11: ${ignore_index}
  12: 7
  13: ${ignore_index}
  14: 1
  15: 2
  16: 2
  17: 3
  18: 4
  19: ${ignore_index}
  20: ${ignore_index}
  21: 5
  22: 8
  23: 9
  24: 10
  25: 11
  26: 12
  27: 13
  28: 14
  29: ${ignore_index}
  30: 15
  31: ${ignore_index}

datamodule:
  _target_: autoware_ml.datamodule.nuscenes.segmentation3d.NuscenesSegmentation3DDataModule
  data_root: ${oc.env:AUTOWARE_ML_DATA_PATH}/nuscenes
  train_ann_file: ${datamodule.data_root}/nuscenes_infos_train.pkl
  val_ann_file: ${datamodule.data_root}/nuscenes_infos_val.pkl
  test_ann_file: ${datamodule.data_root}/nuscenes_infos_val.pkl
  mix_prob: ${mix_prob}
  train_transforms:
    _target_: autoware_ml.transforms.base.TransformsCompose
    pipeline:
      - _target_: autoware_ml.transforms.point_cloud.loading.LoadPointsFromFile
        load_dim: 5
        use_dim: [0, 1, 2, 3]
      - _target_: autoware_ml.transforms.segmentation3d.loading.LoadSegAnnotations3D
        label_mapping: ${seg_label_mapping}
        max_label: ${max_label}
        ignore_index: ${ignore_index}
      - _target_: autoware_ml.transforms.segmentation3d.formatting.PreparePointSegInput
      - _target_: autoware_ml.transforms.point_cloud.geometry.RandomRotate
        angle: [-1.0, 1.0]
        axis: z
        center: [0.0, 0.0, 0.0]
        p: 0.5
      - _target_: autoware_ml.transforms.point_cloud.geometry.RandomScale
        scale: [0.9, 1.1]
      - _target_: autoware_ml.transforms.point_cloud.geometry.RandomFlip
        p: 0.5
      - _target_: autoware_ml.transforms.point_cloud.perturbation.RandomJitter
        sigma: 0.005
        clip: 0.02
      - _target_: autoware_ml.transforms.point_cloud.sampling.GridSample
        grid_size: ${grid_size}
        mode: train
        keys: [coord, strength, segment]
        return_grid_coord: true
      - _target_: autoware_ml.transforms.common.tensor.ToTensor
      - _target_: autoware_ml.transforms.common.packing.Collect
        keys: [coord, grid_coord, segment]
        feat_keys: [coord, strength]
  val_transforms:
    _target_: autoware_ml.transforms.base.TransformsCompose
    pipeline:
      - _target_: autoware_ml.transforms.point_cloud.loading.LoadPointsFromFile
        load_dim: 5
        use_dim: [0, 1, 2, 3]
      - _target_: autoware_ml.transforms.segmentation3d.loading.LoadSegAnnotations3D
        label_mapping: ${seg_label_mapping}
        max_label: ${max_label}
        ignore_index: ${ignore_index}
      - _target_: autoware_ml.transforms.segmentation3d.formatting.PreparePointSegInput
      - _target_: autoware_ml.transforms.point_cloud.sampling.GridSample
        grid_size: ${grid_size}
        mode: train
        keys: [coord, strength, segment]
        return_grid_coord: true
      - _target_: autoware_ml.transforms.common.tensor.ToTensor
      - _target_: autoware_ml.transforms.common.packing.Collect
        keys: [coord, grid_coord, segment]
        feat_keys: [coord, strength]
  test_transforms: ${datamodule.val_transforms}
  predict_transforms:
    _target_: autoware_ml.transforms.base.TransformsCompose
    pipeline:
      - _target_: autoware_ml.transforms.point_cloud.loading.LoadPointsFromFile
        load_dim: 5
        use_dim: [0, 1, 2, 3]
      - _target_: autoware_ml.transforms.segmentation3d.formatting.PreparePointSegInput
      - _target_: autoware_ml.transforms.point_cloud.sampling.GridSample
        grid_size: ${grid_size}
        mode: train
        keys: [coord, strength, segment]
        return_grid_coord: true
      - _target_: autoware_ml.transforms.point_cloud.crop.SphereCrop
        point_max: 4096
        mode: center
      - _target_: autoware_ml.transforms.common.tensor.ToTensor
      - _target_: autoware_ml.transforms.common.packing.Collect
        keys: [coord, grid_coord, segment]
        feat_keys: [coord, strength]
