# @package _global_
defaults:
  - /tasks/segmentation3d/ptv3/tiny
  - /datasets/t4dataset/segmentation3d
  - /datasets/t4dataset/lidar
  - _self_

dataset: ${t4dataset}

batch_size: 8
num_workers: 8

grid_size: 0.12
point_cloud_range: [-122.88, -122.88, -3.0, 122.88, 122.88, 5.0]

datamodule:
  _target_: autoware_ml.datamodule.t4dataset.segmentation3d.T4Segmentation3DDataModule
  data_root: ${dataset.data_root}
  train_ann_file: ${datamodule.data_root}/info/lidarseg/t4dataset_j6gen2_lidarseg_infos_train.pkl
  val_ann_file: ${datamodule.data_root}/info/lidarseg/t4dataset_j6gen2_lidarseg_infos_val.pkl
  test_ann_file: ${datamodule.data_root}/info/lidarseg/t4dataset_j6gen2_lidarseg_infos_test.pkl
  train_dataloader_cfg:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
    shuffle: true
  val_dataloader_cfg:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
  test_dataloader_cfg:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
  train_transforms:
    _target_: autoware_ml.transforms.base.TransformsCompose
    pipeline:
      - _target_: autoware_ml.transforms.point_cloud.loading.LoadPointsFromFile
        load_dim: 5
        use_dim: [0, 1, 2, 3]
      - _target_: autoware_ml.transforms.segmentation3d.loading.LoadSegAnnotations3D
        class_mapping: ${dataset.segmentation3d.class_mapping}
        ignore_index: ${dataset.segmentation3d.ignore_index}
      - _target_: autoware_ml.transforms.point_cloud.formatting.PreparePointCloudInput
      - _target_: autoware_ml.transforms.segmentation3d.formatting.PreparePointSegInput
      - _target_: autoware_ml.transforms.point_cloud.geometry.GlobalRotScaleTrans
        rot_range: [-3.14159, 3.14159]
        scale_ratio_range: [0.9, 1.1]
      - _target_: autoware_ml.transforms.point_cloud.geometry.RandomFlip3D
        flip_ratio_bev_horizontal: 0.5
        flip_ratio_bev_vertical: 0.5
      - _target_: autoware_ml.transforms.point_cloud.crop.PointsRangeFilter
        point_cloud_range: ${point_cloud_range}
      - _target_: autoware_ml.transforms.point_cloud.perturbation.RandomJitter
        sigma: 0.005
        clip: 0.02
      - _target_: autoware_ml.transforms.point_cloud.crop.SphereCrop
        point_max: 128000
        mode: random
      - _target_: autoware_ml.transforms.common.copying.Copy
        keys_dict: { segment: origin_segment, coord: origin_coord }
      - _target_: autoware_ml.transforms.point_cloud.sampling.GridSample
        grid_size: ${grid_size}
        point_cloud_range: ${point_cloud_range}
        hash_type: fnv
        mode: train
        keys: [coord, strength, segment]
        return_inverse: true
        return_grid_coord: true
      - _target_: autoware_ml.transforms.common.packing.BuildPointFeatures
        keys: [coord, strength]
        output_key: feat
  val_transforms:
    _target_: autoware_ml.transforms.base.TransformsCompose
    pipeline:
      - _target_: autoware_ml.transforms.point_cloud.loading.LoadPointsFromFile
        load_dim: 5
        use_dim: [0, 1, 2, 3]
      - _target_: autoware_ml.transforms.segmentation3d.loading.LoadSegAnnotations3D
        class_mapping: ${dataset.segmentation3d.class_mapping}
        ignore_index: ${dataset.segmentation3d.ignore_index}
      - _target_: autoware_ml.transforms.point_cloud.formatting.PreparePointCloudInput
      - _target_: autoware_ml.transforms.segmentation3d.formatting.PreparePointSegInput
      - _target_: autoware_ml.transforms.point_cloud.crop.PointsRangeFilter
        point_cloud_range: ${point_cloud_range}
      - _target_: autoware_ml.transforms.common.copying.Copy
        keys_dict: { segment: origin_segment, coord: origin_coord }
      - _target_: autoware_ml.transforms.point_cloud.sampling.GridSample
        grid_size: ${grid_size}
        point_cloud_range: ${point_cloud_range}
        hash_type: fnv
        mode: test
        keys: [coord, strength, segment]
        return_inverse: true
        return_grid_coord: true
      - _target_: autoware_ml.transforms.common.packing.BuildPointFeatures
        keys: [coord, strength]
        output_key: feat
  test_transforms: ${datamodule.val_transforms}
  predict_transforms:
    _target_: autoware_ml.transforms.base.TransformsCompose
    pipeline:
      - _target_: autoware_ml.transforms.point_cloud.loading.LoadPointsFromFile
        load_dim: 5
        use_dim: [0, 1, 2, 3]
      - _target_: autoware_ml.transforms.point_cloud.formatting.PreparePointCloudInput
      - _target_: autoware_ml.transforms.segmentation3d.formatting.PreparePointSegInput
      - _target_: autoware_ml.transforms.point_cloud.crop.PointsRangeFilter
        point_cloud_range: ${point_cloud_range}
      - _target_: autoware_ml.transforms.point_cloud.sampling.GridSample
        grid_size: ${grid_size}
        point_cloud_range: ${point_cloud_range}
        hash_type: fnv
        mode: test
        keys: [coord, strength]
        return_inverse: true
        return_grid_coord: true
      - _target_: autoware_ml.transforms.common.packing.BuildPointFeatures
        keys: [coord, strength]
        output_key: feat
