# @package _global_
defaults:
  - /tasks/calibration_status/calibration_status_classifier/resnet18_base
  - /database@database: nuscenes/nuscenes_base
  - /datamodule@datamodule: nuscenes/default_calibration_status_datamodule
  - /datasets/nuscenes/camera
  - _self_

# One sample per camera
camera_sources: ${nuscenes.camera.camera_order}
