# @package _global_
defaults:
  - /tasks/calibration_status/calibration_status_classifier/resnet18_base
  - /database@database: t4dataset/t4dataset_j6gen2_base
  - /datamodule@datamodule: t4dataset/default_calibration_status_datamodule
  - /datasets/t4dataset/camera
  - _self_

# One sample per camera
camera_sources: ${t4dataset.camera.camera_order}
