# @package _global_
defaults:
  - /defaults/default_runtime
  - _self_

batch_size: 8
num_workers: 8

datamodule:
  train_dataset:
    camera_sources: ${camera_sources}
  validation_dataset:
    camera_sources: ${camera_sources}
  test_dataset:
    camera_sources: ${camera_sources}
  train_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
    shuffle: true
  validation_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
  test_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}

model:
  _target_: autoware_ml.models.calibration_status.calibration_status.CalibrationStatusClassifier
  backbone:
    _target_: autoware_ml.models.common.backbones.resnet.ResNet18
    in_channels: 5
  neck:
    _target_: autoware_ml.models.common.necks.global_average_pooling.GlobalAveragePooling
  head:
    _target_: autoware_ml.models.common.heads.linear_cls_head.LinearClsHead
    num_classes: 2
    in_channels: 512
    loss:
      _target_: torch.nn.CrossEntropyLoss
    topk: [1]
    cal_acc: true
  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.001
    weight_decay: 0.01
    betas: [0.9, 0.999]
    eps: 1e-8
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    T_max: 30
    eta_min: 1e-8
    last_epoch: -1

trainer:
  max_epochs: 30
  gradient_clip_val: 10.0
  gradient_clip_algorithm: norm

deploy:
  onnx:
    modules:
      end_to_end:
        input_names: [input]
        output_names: [output]
        dynamic_shapes:
          fused_img: { 2: height, 3: width }
  tensorrt:
    input_shapes:
      input:
        min_shape: [1, 5, 1080, 1920]
        opt_shape: [1, 5, 1860, 2880]
        max_shape: [1, 5, 2160, 3840]
