# @package _global_
defaults:
  - /defaults/default_runtime
  - _self_

batch_size: 8
num_workers: 8

# [x_min, y_min, z_min, x_max, y_max, z_max]
ego_box: [-1.53, -1.15, -0.1, 5.72, 1.15, 3.1]

datamodule:
  train_dataset:
    camera_sources: ${camera_sources}
    transforms:
      _target_: autoware_ml.transforms.base.TransformsCompose
      _convert_: all
      pipeline:
        - _target_: autoware_ml.transforms.camera.loading.LoadImagesFromFile
          _convert_: all
        - _target_: autoware_ml.transforms.point_cloud.loading.LoadPointsFromFile
          _convert_: all
          load_dim: ${database.lidar_pointcloud_num_features}
          use_dim: [0, 1, 2, 3]
          bev_remove_radius: 0.0
        - _target_: autoware_ml.transforms.point_cloud.geometry.CropBoxInner
          _convert_: all
          crop_box: ${ego_box}
        - _target_: autoware_ml.transforms.camera.distortion.UndistortImage
          _convert_: all
          alpha: 0.0
        - _target_: autoware_ml.transforms.camera_lidar.camera_lidar.CalibrationMisalignment
          _convert_: all
          probability: 0.5
          activate_roll: true
          activate_pitch: true
          activate_yaw: true
          activate_x: true
          activate_y: true
          activate_z: true
          min_roll_neg: 0.2
          max_roll_neg: 0.4
          min_roll_pos: 0.2
          max_roll_pos: 0.4
          min_pitch_neg: 0.2
          max_pitch_neg: 0.4
          min_pitch_pos: 0.2
          max_pitch_pos: 0.4
          min_yaw_neg: 4.2
          max_yaw_neg: 8.4
          min_yaw_pos: 4.2
          max_yaw_pos: 8.4
          min_x_neg: 0.22
          max_x_neg: 0.44
          min_x_pos: 0.22
          max_x_pos: 0.44
          min_y_neg: 0.12
          max_y_neg: 0.24
          min_y_pos: 0.06
          max_y_pos: 0.12
          min_z_neg: 0.24
          max_z_neg: 0.48
          min_z_pos: 0.54
          max_z_pos: 1.08
        - _target_: autoware_ml.transforms.camera.geometry.CropAndScale
          _convert_: all
          probability: 0.2
          crop_ratio: 0.8
        - _target_: autoware_ml.transforms.camera_lidar.camera_lidar.Affine
          _convert_: all
          probability: 0.2
          max_distortion: 0.05
        - _target_: autoware_ml.transforms.image.image.PhotometricDistortion
          _convert_: all
          probability: 0.2
          brightness: 0.1
          contrast: 0.1
          saturation: 0.1
          hue: 0.05
        - _target_: autoware_ml.transforms.camera_lidar.camera_lidar.LidarCameraFusion
          _convert_: all
          max_depth: 128.0
          dilation_size: 1
          ego_box: ${ego_box}
        - _target_: autoware_ml.transforms.camera_lidar.camera_lidar.SaveFusionPreview
          _convert_: all
          probability: 0.00001
          out_dir: ${hydra:run.dir}/previews
          max_depth: 128.0
          alpha: 1.0
          depth_colormap: jet
  test_dataset:
    camera_sources: ${camera_sources}
    transforms:
      _target_: autoware_ml.transforms.base.TransformsCompose
      _convert_: all
      pipeline:
        - _target_: autoware_ml.transforms.camera.loading.LoadImagesFromFile
          _convert_: all
        - _target_: autoware_ml.transforms.point_cloud.loading.LoadPointsFromFile
          _convert_: all
          load_dim: ${database.lidar_pointcloud_num_features}
          use_dim: [0, 1, 2, 3]
          bev_remove_radius: 0.0
        - _target_: autoware_ml.transforms.point_cloud.geometry.CropBoxInner
          _convert_: all
          crop_box: ${ego_box}
        - _target_: autoware_ml.transforms.camera.distortion.UndistortImage
          _convert_: all
          alpha: 0.0
        - _target_: autoware_ml.transforms.camera_lidar.camera_lidar.CalibrationMisalignment
          _convert_: all
          probability: 0.5
          activate_roll: true
          activate_pitch: true
          activate_yaw: true
          activate_x: true
          activate_y: true
          activate_z: true
          min_roll_neg: 0.2
          max_roll_neg: 0.4
          min_roll_pos: 0.2
          max_roll_pos: 0.4
          min_pitch_neg: 0.2
          max_pitch_neg: 0.4
          min_pitch_pos: 0.2
          max_pitch_pos: 0.4
          min_yaw_neg: 4.2
          max_yaw_neg: 8.4
          min_yaw_pos: 4.2
          max_yaw_pos: 8.4
          min_x_neg: 0.22
          max_x_neg: 0.44
          min_x_pos: 0.22
          max_x_pos: 0.44
          min_y_neg: 0.12
          max_y_neg: 0.24
          min_y_pos: 0.06
          max_y_pos: 0.12
          min_z_neg: 0.24
          max_z_neg: 0.48
          min_z_pos: 0.54
          max_z_pos: 1.08
        - _target_: autoware_ml.transforms.camera_lidar.camera_lidar.LidarCameraFusion
          _convert_: all
          max_depth: 128.0
          dilation_size: 1
          ego_box: ${ego_box}
  train_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
    shuffle: true
  validation_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
  test_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}

model:
  _target_: autoware_ml.models.calibration_status.calibration_status.CalibrationStatusClassifier
  backbone:
    _target_: autoware_ml.models.common.backbones.resnet.ResNet18
    in_channels: 5
  neck:
    _target_: autoware_ml.models.common.necks.global_average_pooling.GlobalAveragePooling
  head:
    _target_: autoware_ml.models.common.heads.linear_cls_head.LinearClsHead
    num_classes: 2
    in_channels: 512
    loss:
      _target_: torch.nn.CrossEntropyLoss
    topk: [1]
    cal_acc: true
  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.001
    weight_decay: 0.01
    betas: [0.9, 0.999]
    eps: 1e-8
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    T_max: 30
    eta_min: 1e-8
    last_epoch: -1

trainer:
  max_epochs: 30
  gradient_clip_val: 10.0
  gradient_clip_algorithm: norm

deploy:
  onnx:
    modules:
      end_to_end:
        input_names: [input]
        output_names: [output]
        dynamic_shapes:
          fused_img: { 2: height, 3: width }
  tensorrt:
    input_shapes:
      input:
        min_shape: [1, 5, 1080, 1920]
        opt_shape: [1, 5, 1860, 2880]
        max_shape: [1, 5, 2160, 3840]
