# @package nuscenes.segmentation3d

defaults:
  - /datasets/nuscenes/base
  - _self_

ignore_index: ${database.taxonomy.segmentation3d.ignore_index}
class_names: ${database.taxonomy.segmentation3d.class_names}
num_classes: ${class_count:${database.taxonomy.segmentation3d.class_names}}
metrics:
  - _target_: autoware_ml.metrics.segmentation3d.suite.Segmentation3DConfusionMatrixMetricSuite
    components:
      - { _target_: autoware_ml.metrics.segmentation3d.iou.IoU, stages: [val, test] }
      - { _target_: autoware_ml.metrics.segmentation3d.accuracy.Accuracy, stages: [val, test] }
      - { _target_: autoware_ml.metrics.segmentation3d.precision_recall_f1.PrecisionRecallF1, stages: [val, test] }
    num_classes: ${nuscenes.segmentation3d.num_classes}
    ignore_index: ${nuscenes.segmentation3d.ignore_index}
    class_names: ${nuscenes.segmentation3d.class_names}
    ranges:
      - { _target_: autoware_ml.metrics.base.MetricRange, name: 0-50m, min_distance: 0.0, max_distance: 50.0 }
      - { _target_: autoware_ml.metrics.base.MetricRange, name: 50-90m, min_distance: 50.0, max_distance: 90.0 }
      - { _target_: autoware_ml.metrics.base.MetricRange, name: 90-121m, min_distance: 90.0, max_distance: 121.0 }
      - { _target_: autoware_ml.metrics.base.MetricRange, name: 0-121m, min_distance: 0.0, max_distance: 121.0 }
