defaults:
  - t4dataset/t4dataset_common@_here_
  - t4dataset/scenarios@scenarios.db_j6gen2_segdet3d: detection3d_segmentation3d/db_j6gen2_segdet3d
  - _self_

version: T4Dataset-j6gen2_segdet3d-v1.0.0
cache_path: ${cache_root_path}/detection3d_segmentation3d/
lidar_pointcloud_num_features: 7
