# Read each database into their corresponding scenarios, it will run evaluation/visualization on each scenario
defaults:
  - t4dataset/t4dataset_common@_here_
  - t4dataset/scenarios@scenarios.db_base: detection3d/db_base
  - t4dataset/scenarios@scenarios.db_j6gen2_base: detection3d/db_j6gen2_base
  - t4dataset/scenarios@scenarios.db_j6gen2: detection3d/db_j6gen2
  - t4dataset/scenarios@scenarios.db_jpntaxi_base: detection3d/db_jpntaxi_base
  - t4dataset/scenarios@scenarios.db_largebus: detection3d/db_largebus
  - _self_

version: T4Dataset-base-v1.0.0
# Caches
cache_path: ${cache_root_path}/detection3d/
