defaults:
  - t4dataset/t4dataset_common@_here_
  - t4dataset/scenarios@scenarios.db_jpntaxi_base: detection3d/db_jpntaxi_base
  - _self_

version: T4Dataset-jpntaxi_base-v1.0.0
cache_path: ${cache_root_path}/detection3d/
