version: jpntaxi_base_v1.0.0
# List of database versions and each yaml file consists of train/val/test splits
db_versions:
  - _target_: autoware_ml.databases.scenarios.DatabaseVersion
    _convert_: all
    db_version: db_jpntaxigen2_v1
    max_sweeps: 2
    sample_steps: 1
  - _target_: autoware_ml.databases.scenarios.DatabaseVersion
    _convert_: all
    db_version: db_jpntaxigen2_v2
    max_sweeps: 2
    sample_steps: 1
  - _target_: autoware_ml.databases.scenarios.DatabaseVersion
    _convert_: all
    db_version: db_jpntaxi_v1
    max_sweeps: 2
    sample_steps: 1
  - _target_: autoware_ml.databases.scenarios.DatabaseVersion
    _convert_: all
    db_version: db_jpntaxi_v2
    max_sweeps: 2
    sample_steps: 1
  - _target_: autoware_ml.databases.scenarios.DatabaseVersion
    _convert_: all
    db_version: db_jpntaxi_v4
    max_sweeps: 2
    sample_steps: 1
