# @package _global_

hydra:
  run:
    dir: mlruns/${user_config_name:${hydra:job.config_name}}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: mlruns/optuna/${user_config_name:${hydra:job.config_name}}/${now:%Y-%m-%d}/${now:%H-%M-%S}
