# Copyright 2025 TIER IV, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Calibration status classification model wrappers.

This module contains the task-level model wrapper used for calibration status
classification experiments and deployment flows.
"""

from collections.abc import Sequence
from typing import Any

import torch
import torch.nn as nn

from autoware_ml.models.base import BaseModel


class CalibrationStatusClassifier(BaseModel):
    """Predict calibration-status labels from fused image inputs.

    The model combines a backbone, neck, and classification head inside the
    shared Autoware-ML training interface.
    """

    def __init__(
        self,
        backbone: nn.Module,
        neck: nn.Module,
        head: nn.Module,
        **kwargs: Any,
    ) -> None:
        """Initialize the calibration-status classifier.

        Args:
            backbone: Feature extraction backbone for fused camera inputs.
            neck: Intermediate feature aggregation module.
            head: Classification head that computes logits, predictions, and losses.
            **kwargs: Additional keyword arguments forwarded to :class:`BaseModel`.
        """
        super().__init__(**kwargs)

        self.backbone = backbone
        self.neck = neck
        self.head = head

    def forward(self, fused_img: torch.Tensor) -> torch.Tensor:
        """Run the classifier on fused image inputs.

        Args:
            fused_img: Batched fused image tensor.

        Returns:
            Classification logits for each sample.
        """
        feats = self.backbone(fused_img)
        feats = self.neck(feats)
        logits = self.head(feats)
        return logits

    @torch.no_grad()
    def predict(self, fused_img: torch.Tensor) -> torch.Tensor:
        """Return predicted calibration-status labels.

        Args:
            fused_img: Batched fused image tensor.

        Returns:
            Predicted task outputs generated by the classification head.
        """
        logits = self(fused_img)
        return self.head.predict(logits)

    def compute_metrics(
        self,
        outputs: torch.Tensor | Sequence[torch.Tensor],
        gt_calibration_status: torch.Tensor,
    ) -> dict[str, torch.Tensor]:
        """Compute training losses and metrics for one batch.

        Args:
            outputs: Model outputs returned by :meth:`forward`.
            gt_calibration_status: Ground-truth calibration-status labels.

        Returns:
            Dictionary of loss terms and logged metrics.
        """
        return self.head.loss(outputs, gt_calibration_status)
