# @package _global_
defaults:
  - /tasks/multi/ptv3/tiny
  - /datasets/t4dataset/detection3d
  - /datasets/t4dataset/segmentation3d
  - /datasets/t4dataset/lidar
  - /database@database: t4dataset/t4dataset_j6gen2_segdet3d
  - /datamodule@datamodule: t4dataset/default_segdet3d_datamodule
  - _self_

dataset: ${t4dataset}

# Classes with partial masks
partial_detection_classes: [motorcycle, bicycle, pedestrian, traffic_cone]

t4dataset:
  segmentation3d:
    point_components_extra:
      - _target_: autoware_ml.metrics.segmentation3d.partial_detection.PartialDetectionScore
        stages: [test]
        det_class_names: ${t4dataset.detection3d.class_names}
        seg_class_names: ${t4dataset.segmentation3d.class_names}
        class_names: ${partial_detection_classes}
      - _target_: autoware_ml.metrics.segmentation3d.partial_detection.PartialDetectionScore
        stages: [test]
        det_class_names: ${t4dataset.detection3d.class_names}
        seg_class_names: ${t4dataset.segmentation3d.class_names}
        class_names: ${partial_detection_classes}
        filter: ${t4dataset.segmentation3d.region_filters.road}
      - _target_: autoware_ml.metrics.segmentation3d.partial_detection.PartialDetectionScore
        stages: [test]
        det_class_names: ${t4dataset.detection3d.class_names}
        seg_class_names: ${t4dataset.segmentation3d.class_names}
        class_names: ${partial_detection_classes}
        filter: ${t4dataset.segmentation3d.region_filters.walkway}
      - _target_: autoware_ml.metrics.segmentation3d.partial_detection.PartialDetectionScore
        stages: [test]
        det_class_names: ${t4dataset.detection3d.class_names}
        seg_class_names: ${t4dataset.segmentation3d.class_names}
        class_names: ${partial_detection_classes}
        filter: ${t4dataset.segmentation3d.corridor_filter}
      - _target_: autoware_ml.metrics.segmentation3d.partial_detection.PartialDetectionScore
        stages: [test]
        det_class_names: ${t4dataset.detection3d.class_names}
        seg_class_names: ${t4dataset.segmentation3d.class_names}
        class_names: ${partial_detection_classes}
        filter: ${t4dataset.segmentation3d.collision_filter}

point_cloud_range: [-122.88, -122.88, -3.0, 122.88, 122.88, 5.0]
grid_size: 0.12
head_voxel_size: [0.96, 0.96, 8.0]

num_proposals: 500

batch_size: 8
num_workers: 8

datamodule:
  train_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
    shuffle: true
  validation_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
  test_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}

model:
  bev_neck:
    bev_projector:
      output_shape: [256, 256]
      assume_valid_grid_coord: true
  bbox_head:
    nms_type: circle
    nms_min_radius: 1.0
    nms_groups:
      - class_names: [car, truck, bus]
        nms_radius: 0.25
        post_max_size: 300
      - class_names: [motorcycle, bicycle]
        nms_radius: 0.5
        post_max_size: 100
      - class_names: [pedestrian]
        nms_radius: 0.0
        post_max_size: 100
      - class_names: [traffic_cone]
        nms_radius: 0.0
        post_max_size: 100
      - class_names: [barrier]
        nms_radius: 0.0
        post_max_size: 50
      - class_names: [animal]
        nms_radius: 0.0
        post_max_size: 50
      - class_names: [debris]
        nms_radius: 0.0
        post_max_size: 50
    bbox_coder:
      post_center_range: [-132.88, -132.88, -5.0, 132.88, 132.88, 12.0]
      score_threshold: [0.015, 0.010, 0.010, 0.020, 0.020, 0.030, 0.030, 0.020, 0.040, 0.020]
