# @package _global_

# Stage 2: pseudo label pretraining

defaults:
  - /tasks/multi/ptv3/voxel012_122m_t4dataset_j6gen2
  - /database@j6gen2_database: t4dataset/t4dataset_j6gen2_pseudo
  - /database@seg3d_gt_database: t4dataset/t4dataset_j6gen2_semaseg
  - override /database@database: t4dataset/t4dataset_base_pseudo
  - _self_

datamodule:
  train_sources:
    - database: ${database}
      det3d: true
      seg3d: false
      repeat: 1
    - database: ${j6gen2_database}
      det3d: true
      seg3d: true
      repeat: 1
    - database: ${seg3d_gt_database}
      det3d: false
      seg3d: true
      repeat: 6
  validation_sources:
    - database: ${j6gen2_database}
      det3d: true
      seg3d: false
      repeat: 1
    - database: ${seg3d_gt_database}
      det3d: false
      seg3d: true
      repeat: 1

model:
  optimizer:
    lr: 0.0001
  optimizer_group_overrides:
    encoder_block:
      lr: 0.00001
    encoder_default:
      lr: 0.000025
    seg3d_head:
      lr: 0.00005
  scheduler:
    warmup_epochs: 4
    decay_epochs: 20
    max_lr_factor: 5.0

trainer:
  max_epochs: 24

callbacks:
  early_stopping: null
