# @package _global_
defaults:
  - /tasks/multi/ptv3/base
  - /datasets/nuscenes/detection3d
  - /datasets/nuscenes/segmentation3d
  - /datasets/nuscenes/lidar
  - /database@database: nuscenes/nuscenes_base
  - /datamodule@datamodule: nuscenes/default_segdet3d_datamodule
  - _self_

dataset: ${nuscenes}

batch_size: 16
num_workers: 8

grid_size: 0.05
point_cloud_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]

global_rot_scale_trans:
  yaw_rot_range: [-1.57079633, 1.57079633]
  scale_ratio_range: [0.8, 1.2]
  translation_std: [1.0, 1.0, 0.2]

head_voxel_size: [0.4, 0.4, 8.0]

num_proposals: 200

datamodule:
  train_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
    shuffle: true
  validation_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
  test_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}

model:
  bev_neck:
    bev_projector:
      output_shape: [256, 256]
      assume_valid_grid_coord: true
  bbox_head:
    nms_min_radius: 1.0
    bbox_coder:
      post_center_range: [-61.2, -61.2, -10.0, 61.2, 61.2, 10.0]
