# @package _global_
defaults:
  - /tasks/multi/ptv3/tiny
  - /datasets/t4dataset/detection3d
  - /datasets/t4dataset/segmentation3d
  - /datasets/t4dataset/segdet3d: default_coarse
  - /datasets/t4dataset/lidar
  - /database@database: t4dataset/t4dataset_j6gen2_segdet3d
  - /datamodule@datamodule: t4dataset/default_segdet3d_datamodule
  - /datamodule/frame_sampling@datamodule.train_frame_sampling: default_frame_sampling
  - _self_

dataset: ${t4dataset}

point_cloud_range: [-122.88, -122.88, -3.0, 122.88, 122.88, 5.0]
max_voxels: 524288
grid_size: 0.12

head_voxel_size: [0.96, 0.96, 8.0]

num_proposals: 500

batch_size: 8
num_workers: 8

datamodule:
  train_dataset:
    transforms:
      _target_: autoware_ml.transforms.base.TransformsCompose
      _convert_: all
      pipeline:
        - _target_: autoware_ml.transforms.point_cloud.loading.LoadPointsFromFile
          _convert_: all
          use_dim: [0, 1, 2, 3]
          bev_remove_radius: 0.0
        - _target_: autoware_ml.transforms.point_cloud.loading.LoadMultiSweepPointsFromFile
          _convert_: all
          past:
            _target_: autoware_ml.transforms.point_cloud.loading.SweepWindow
            num: 1
            time_lag_range: [0.05, 0.25]
            selection: random
          bev_remove_radius: 1.0
          use_timestamp_difference: true
          use_dim: [0, 1, 2, 3]
        - _target_: autoware_ml.transforms.point_cloud.geometry.RandomRotateTargetAngle
          _convert_: all
          probability: 0.75
          # Multiples of pi
          yaw_angle_ratios: [0.5, 1.0, 1.5]
        - _target_: autoware_ml.transforms.point_cloud.geometry.GlobalRotScaleTrans
          _convert_: all
          yaw_rot_range: [-1.57079633, 1.57079633]
          scale_ratio_range: [0.9, 1.1]
          translation_std: [0.5, 0.5, 0.2]
        - _target_: autoware_ml.transforms.point_cloud.geometry.GlobalBEVRandomFlip
          _convert_: all
          horizontal_flip_ratio: 0.5
          vertical_flip_ratio: 0.5
        - _target_: autoware_ml.transforms.point_cloud.perturbation.RandomJitter
          _convert_: all
          sigma: 0.012
          clip: 0.05
        - _target_: autoware_ml.transforms.point_cloud.geometry.PointsRangeFilter
          _convert_: all
          points_range: ${point_cloud_range}
        - _target_: autoware_ml.transforms.point_cloud.sampling.RandomDropout
          _convert_: all
          probability: 0.5
          dropout_ratio: 0.2
        - _target_: autoware_ml.transforms.point_cloud.perturbation.RandomStrengthJitter
          _convert_: all
          gamma_range: [0.8, 1.25]
          scale_range: [0.9, 1.1]
          shift_range: [-0.02, 0.02]
        - _target_: autoware_ml.transforms.boxes3d.filters.BBoxesLabelNameFilter
          _convert_: all
          label_names_to_keep: ${database.taxonomy.detection3d.class_names}
          class_names: ${database.taxonomy.detection3d.class_names}
        - _target_: autoware_ml.transforms.boxes3d.filters.BBoxesAttributeFilter
          _convert_: all
          filter_attributes: ${dataset.detection3d.filter_attributes}
        - _target_: autoware_ml.transforms.boxes3d.filters.BBoxesRangeFilter
          _convert_: all
          point_cloud_range: ${point_cloud_range}
        - _target_: autoware_ml.transforms.boxes3d.filters.BBoxesMinPointsFilter
          _convert_: all
          min_points: 2
          bev_range:
            - ${point_cloud_range.0}
            - ${point_cloud_range.1}
            - ${point_cloud_range.3}
            - ${point_cloud_range.4}
        - _target_: autoware_ml.transforms.boxes3d.filters.BBoxesMinPointsFilter
          _convert_: all
          min_points: 3
          bev_range: [-60.0, -60.0, 60.0, 60.0]
  test_dataset:
    transforms:
      _target_: autoware_ml.transforms.base.TransformsCompose
      _convert_: all
      pipeline:
        - _target_: autoware_ml.transforms.point_cloud.loading.LoadPointsFromFile
          _convert_: all
          use_dim: [0, 1, 2, 3]
          bev_remove_radius: 0.0
        - _target_: autoware_ml.transforms.point_cloud.loading.LoadMultiSweepPointsFromFile
          _convert_: all
          past:
            _target_: autoware_ml.transforms.point_cloud.loading.SweepWindow
            num: 1
            time_lag_range: [0.05, 0.25]
            selection: nearest
          bev_remove_radius: 1.0
          use_timestamp_difference: true
          use_dim: [0, 1, 2, 3]
        - _target_: autoware_ml.transforms.point_cloud.geometry.PointsRangeFilter
          _convert_: all
          points_range: ${point_cloud_range}
        - _target_: autoware_ml.transforms.boxes3d.filters.BBoxesLabelNameFilter
          _convert_: all
          label_names_to_keep: ${database.taxonomy.detection3d.class_names}
          class_names: ${database.taxonomy.detection3d.class_names}
        - _target_: autoware_ml.transforms.boxes3d.filters.BBoxesAttributeFilter
          _convert_: all
          filter_attributes: ${dataset.detection3d.filter_attributes}
        - _target_: autoware_ml.transforms.boxes3d.filters.BBoxesRangeFilter
          _convert_: all
          point_cloud_range: ${point_cloud_range}
  train_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
    shuffle: false
  validation_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
  test_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
  train_frame_sampling:
    pedestrian_class_name: pedestrian

model:
  bev_neck:
    bev_projector:
      output_shape: [256, 256]
      assume_valid_grid_coord: true
  bbox_head:
    nms_type: circle
    nms_min_radius: 1.0
    nms_groups:
      - class_names: [car, truck, bus]
        nms_radius: 0.25
        post_max_size: 300
      - class_names: [motorcycle, bicycle]
        nms_radius: 0.5
        post_max_size: 100
      - class_names: [pedestrian]
        nms_radius: 0.0
        post_max_size: 100
      - class_names: [traffic_cone]
        nms_radius: 0.0
        post_max_size: 100
      - class_names: [barrier]
        nms_radius: 0.0
        post_max_size: 50
      - class_names: [animal]
        nms_radius: 0.0
        post_max_size: 50
      - class_names: [debris]
        nms_radius: 0.0
        post_max_size: 50
    bbox_coder:
      post_center_range: [-132.88, -132.88, -5.0, 132.88, 132.88, 12.0]
      score_threshold: [0.015, 0.010, 0.010, 0.020, 0.020, 0.030, 0.030, 0.020, 0.040, 0.020]
