# @package _global_
defaults:
  - /tasks/detection3d/centerpoint/base
  - /datasets/nuscenes/detection3d
  - /datasets/nuscenes/lidar
  - /database@database: nuscenes/nuscenes_base
  - /datamodule@datamodule: nuscenes/default_detection3d_datamodule
  - override /datamodule/transforms@datamodule.train_dataset.transforms: centerpoint_nuscenes_train_transforms
  - override /datamodule/transforms@datamodule.test_dataset.transforms: centerpoint_nuscenes_test_transforms
  - _self_

batch_size: 16
num_workers: 8

dataset: ${nuscenes}

point_cloud_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
voxel_size: [0.2, 0.2, 8.0]

model:
  pts_middle_encoder:
    output_shape: [512, 512]
  pts_backbone:
    layer_strides: [2, 2, 2]
  bbox_head:
    out_size_factor: 4
    nms_min_radius: 1.0
  scheduler:
    max_lr_factor: 10.0

datamodule:
  train_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
    shuffle: true
  validation_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
  test_dataloader:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
