_target_: autoware_ml.transforms.base.TransformsCompose
_convert_: all

pipeline:
  - _target_: autoware_ml.transforms.point_cloud.loading.LoadPointsFromFile
    _convert_: all

    load_dim: ${database.lidar_pointcloud_num_features}
    use_dim: [0, 1, 2, 3] # Refer PointFieldIndex for the name of each dimensionality, [x, y, z, intensity]
    bev_remove_radius: 0.0

  - _target_: autoware_ml.transforms.point_cloud.geometry.RandomRotateTargetAngle
    _convert_: all

    probability: 0.75
    # Multiples of pi
    yaw_angle_ratios: [0.5, 1.0, 1.5]

  - _target_: autoware_ml.transforms.point_cloud.geometry.GlobalRotScaleTrans
    _convert_: all

    # In radians, the range of rotation angles for random rotation around the Z-axis.
    yaw_rot_range: [-1.57079633, 1.57079633]
    # The range of scale factors for random scaling.
    scale_ratio_range: [0.9, 1.1]
    # The standard deviation for Gaussian translation noise.
    translation_std: [0.5, 0.5, 0.2]

  - _target_: autoware_ml.transforms.point_cloud.geometry.GlobalBEVRandomFlip
    _convert_: all

    horizontal_flip_ratio: 0.5
    vertical_flip_ratio: 0.5

  - _target_: autoware_ml.transforms.point_cloud.perturbation.RandomJitter
    _convert_: all

    sigma: 0.012
    clip: 0.05

  - _target_: autoware_ml.transforms.point_cloud.geometry.PointsRangeFilter
    _convert_: all

    points_range: ${point_cloud_range}

  - _target_: autoware_ml.transforms.point_cloud.sampling.RandomDropout
    _convert_: all

    probability: 0.5
    dropout_ratio: 0.2

  - _target_: autoware_ml.transforms.point_cloud.perturbation.RandomStrengthJitter
    _convert_: all

    gamma_range: [0.8, 1.25]
    scale_range: [0.9, 1.1]
    shift_range: [-0.02, 0.02]

  - _target_: autoware_ml.transforms.boxes3d.filters.BBoxesLabelNameFilter
    _convert_: all

    label_names_to_keep: ${database.taxonomy.detection3d.class_names}
    class_names: ${database.taxonomy.detection3d.class_names}

  - _target_: autoware_ml.transforms.boxes3d.filters.BBoxesAttributeFilter
    _convert_: all

    filter_attributes: ${dataset.detection3d.filter_attributes}

  - _target_: autoware_ml.transforms.boxes3d.filters.BBoxesBEVDistanceFilter
    _convert_: all

    bev_range:
      - ${point_cloud_range.0}
      - ${point_cloud_range.1}
      - ${point_cloud_range.3}
      - ${point_cloud_range.4}

  # Order matters, it first filters bboxes over the whole range with less than 2 points.
  # Then it filters bboxes within 60 meters with less than 3 points
  - _target_: autoware_ml.transforms.boxes3d.filters.BBoxesMinPointsFilter
    _convert_: all

    min_points: 2
    bev_range:
      - ${point_cloud_range.0}
      - ${point_cloud_range.1}
      - ${point_cloud_range.3}
      - ${point_cloud_range.4}

  - _target_: autoware_ml.transforms.boxes3d.filters.BBoxesMinPointsFilter
    _convert_: all

    min_points: 3
    bev_range: [-60.0, -60.0, 60.0, 60.0]
