name: require-build-and-test-label

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  label-required:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Require run:build-and-test label
        run: |
          if [ "${{ contains(github.event.pull_request.labels.*.name, 'run:build-and-test') }}" != "true" ]; then
            echo "The pull request must have the 'run:build-and-test' label." >&2
            exit 1
          fi
